### PR TITLE
Use simplejson when it's available

### PR DESCRIPTION
**Pull request by dnephin**
Also run tests against python2.7

### CODE REVIEW

**Comment by prat0318** [comment]
lgtm.

**Comment by dnephin** [comment]
rebased so this can be merged, but for some reason travis isn't starting a build yet.

**Comment by prat0318** [comment]
May be because of this...
screen shot 2015-02-25 at 4 59 49 pm

**Comment by dnephin** [comment]
That explains why my other builds are taking forever

**Pull request merged**
