### PR TITLE
swagger-spec-validator is a pure python library

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by macisamuele** [comment]
@asottile thanks for updating it.
I would ask to to fix within this PR (if possible) the issue with python 2.6.
Basically jsonschema 2.6.0 drops support for python2.6, since for the moment we would not remove the python 2.6 support could you add a workaround for that? An idea could be something similar to
```python
'jsonschema' if sys.version_info[:2] >= (2, 7) else 'jsonschema<2.6.0'
```

**Comment by asottile** [comment]
In no way is that related to this branch, why are you making me fix your bitrot?

**Comment by macisamuele** [comment]
It was to avoid to open an additional PR for this.
Dropping Python2.6 support seems also a good solution 😄 
🚢

**Comment by asottile** [comment]
Merge?

**Pull request merged**
